apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ExternalName
  externalName: akswebappdb.mysql.database.azure.com # cambiar por el endpoint de azure database mysql de su instancia DB
